pipeline {
  agent any
    stages {
        stage('Build') {
            steps {
                    sh 'echo "mvn -B -DskipTests clean package"'
            }
        }
        stage('Test') {
            steps {
                    sh 'echo "mvn test"'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "success"'
            }
        }
    }
}
